[package]
name = "bitcoin-wallet"
version = "0.2.0"
authors = ["Tamas Blummer <tamas.blummer@gmail.com>"]
license = "Apache-2.0"
homepage = "https://github.com/rust-bitcoin/rust-wallet/"
repository = "https://github.com/rust-bitcoin/rust-wallet/"
documentation = "https://github.com/rust-bitcoin/rust-wallet/"
description = "Wallet library for Bitcoin"
keywords = [ "crypto", "bitcoin" ]
readme = "README.md"

[dependencies]
bitcoin = {version="0.18", features=["bitcoinconsensus", "serde"]}
bitcoin_hashes={version="0.3", features=["serde"]}
secp256k1 = "0.12"
rust-crypto = "0.2"
rand = "0.7"

[dev-dependencies]
serde = "1"
serde_json="1"
hex = "0.3"